[package]
name = "cama-app-gameplay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cama-db = { path = "../cama-db", default-features = false, features = ["gameplay", "match"] }
cama-domain = { path = "../cama-domain" }
chrono.workspace = true
flate2.workspace = true
gif.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
