// Exact flavor catalog shared with the Python Wrapped implementation.

pub const FLAVOR_POOLS: &[(&str, &[&str])] = &[
    (
        "games_played_high",
        &[
            "Your queue button has a restraining order against you",
            "Dota is your full-time job and it doesn't even pay",
            "You have played more Dota than some people have worked",
            "The client remembers you by name at this point",
            "We checked, you have no other hobbies",
            "Your matchmaking queue has its own reserved parking spot",
            "The ancient personally asked you to take a break",
            "Even Gaben thinks you should go outside",
            "Your Steam profile says 'Last Online: Never Offline'",
            "More games than a TI group stage",
            "Roshan respawns faster than you re-queue",
            "You've seen more creep waves than the ocean",
        ],
    ),
    (
        "games_played_mid",
        &[
            "A respectable grind",
            "Not a casual, not yet a degenerate",
            "The sweet spot between fun and concerning",
            "Balanced, as all things should be",
            "Your social life still has a pulse",
            "You haven't lost yourself. Yet.",
            "Enough games to have opinions, not enough to be insufferable",
            "The Goldilocks zone of Dota addiction",
            "Like a Midas — steady and reliable",
            "Your queue discipline rivals a pos 5 player",
        ],
    ),
    (
        "games_played_low",
        &[
            "Did you even play this year?",
            "The lobby barely knows you exist",
            "Touching grass is NOT a legitimate strategy",
            "Casual? Or just scared?",
            "Your absence was noted. And appreciated.",
            "You came, you saw, you queued... once",
            "Rarer than a Roshan Aghs drop",
            "You play Dota like it's a seasonal event",
            "Your hero pool is bigger than your game count",
            "Even couriers have more map time than you",
        ],
    ),
    (
        "win_rate_high",
        &[
            "The team diff was always you",
            "Someone check if they're scripting",
            "Built different, apparently",
            "Winning is a personality trait at this point",
            "The lobby's main character",
            "You hit different, like a Daedalus crit",
            "Enemies see your name and pick defensive lineups",
            "Your win rate is higher than most heroes' pick rates",
            "Basically smurfing on a main account",
            "The Aegis keeps choosing you",
            "Even your losses feel like moral victories",
        ],
    ),
    (
        "win_rate_mid",
        &[
            "Perfectly balanced... painfully average",
            "Coin flip merchant",
            "The matchmaker's dream player",
            "You are exactly where you belong",
            "The definition of mid",
            "Balanced like a 50/50 Roshan fight",
            "Wins and losses cancel out like a Heart toggle",
            "The matchmaker nods approvingly",
            "Flatter than a creep equilibrium line",
            "50% win rate energy — the system working as intended",
        ],
    ),
    (
        "win_rate_low",
        &[
            "We appreciate your service to the other team",
            "They should name a charity after you",
            "At least you're consistent... at losing",
            "Have you considered a different game?",
            "Your W key must be broken",
            "You feed more than a Hand of Midas",
            "The enemy carry sends you thank-you cards",
            "Your throne is basically on a timer",
            "Even Techies has a better win rate",
            "Losing is a strategy. Yours, apparently.",
        ],
    ),
    (
        "teammate_best",
        &[
            "Your carry and your crutch",
            "The duo queue energy is unmistakable",
            "Win together, lose apart",
            "Package deal material right here",
            "When you're on the same team, it's just not fair",
            "Better synergy than Tiny-Io",
            "The Wisp to your Chaos Knight",
            "Lane partners in crime",
            "Two-hero wombo combo potential",
            "Chemistry so good it breaks the shuffler",
        ],
    ),
    (
        "teammate_worst",
        &[
            "Some bonds are forged in shared suffering",
            "Together you form a black hole of MMR",
            "The shuffler keeps pairing you two as a warning",
            "Your combined win rate violates the Geneva Convention",
            "Like a dual offlane — bold, but why?",
            "The anti-synergy is almost impressive",
            "Together you hit like a Quelling Blade on heroes",
        ],
    ),
    (
        "rival_nemesis",
        &[
            "They live rent-free in your head",
            "Every time you see their name, you feel pain",
            "The rivalry that writes itself",
            "You owe them at least one keyboard replacement",
            "Matchmaking's favorite comedy duo",
            "They counter-pick you in real life",
            "Your personal Viper lane matchup",
            "Even Roshan respects this rivalry",
            "You two are like Radiant and Dire — eternally opposed",
            "BKB doesn't block their mental damage to you",
        ],
    ),
    (
        "rival_punching_bag",
        &[
            "Free real estate",
            "They see your name and alt-F4",
            "You own them and everyone knows it",
            "Not even close. Every single time.",
            "Your personal content creator",
            "They're your lane creep and don't even know it",
            "You farm them like a jungle stack",
            "Their name in the lobby is basically a free win",
            "You counter them harder than Meepo counters low MMR",
            "They need a BKB just to handle being on your screen",
        ],
    ),
    (
        "hero_onetrick",
        &[
            "Why learn other heroes when this one just works?",
            "Comfort zone? More like comfort CASTLE",
            "The one-trick pony gallops on",
            "Banning this hero is basically banning you",
            "You and this hero share a Steam account at this point",
            "First pick, every pick, only pick",
            "Your hero pool is a hero puddle",
            "Dotabuff has you listed as this hero's emergency contact",
            "If this hero gets nerfed, you get nerfed",
            "Even Invoker mains have more variety",
        ],
    ),
    (
        "hero_diverse",
        &[
            "Jack of all trades, master of... some?",
            "Your hero pool is an ocean",
            "The versatility is almost concerning",
            "Can you even remember all their abilities?",
            "Last-pick flexibility incarnate",
            "You've played more heroes than most people know exist",
            "Your hero grid is a rainbow",
            "The ultimate flex pick teammate",
            "Draft phase doesn't scare you — it excites you",
            "You've touched more heroes than a Rubick main",
        ],
    ),
    (
        "package_deal",
        &[
            "Friendship has a price. You paid it.",
            "Contractually obligated to play together",
            "The ultimate duo queue energy",
            "Your bond has been legally notarized",
            "Bound by JC and shuffler RNG",
            "A sacred pact sealed in Jopacoins",
            "Friendship isn't free — it costs exactly this much",
            "The shuffler recognizes this arrangement",
            "Duo lane? More like duo LIFE.",
            "Even Io's tether isn't this committed",
        ],
    ),
    (
        "award_gold_goblin",
        &[
            "Farming simulator champion",
            "The creeps file taxes in your name",
            "Every gold coin trembles in your presence",
            "Your GPM makes accountants weep with joy",
            "Alchemist called — he wants his farming techniques back",
            "Last-hitting is a love language and you're fluent",
            "Your Midas is metaphorical AND literal",
            "The neutral camps filed a restraining order",
            "Anti-Mage looks at your farm and cries",
            "Gold doesn't grow on trees — it grows on your hero",
        ],
    ),
    (
        "award_immortal_hands",
        &[
            "Death is beneath them",
            "KDA so clean you could eat off it",
            "Guardian angel in mortal form",
            "Harder to kill than a Bristleback running away",
            "Even Necrophos can't find them in the death timer",
            "Wraith King wishes he had this survival rate",
            "Their buyback gold is basically a savings account",
            "The fountain is a foreign concept to them",
            "They dodge death like a Puck with Phase Shift",
            "Aegis? They don't need an Aegis.",
        ],
    ),
    (
        "award_first_blood_enthusiast",
        &[
            "At least they're consistent",
            "Dying is a form of space creation",
            "Their KDA exists as a cautionary tale",
            "Feeding is just aggressive map control",
            "The grey screen is their second monitor",
            "Bloodstone charges? Negative.",
            "They create space... in the respawn timer",
            "Their death count has its own highlight reel",
            "Even Aegis can't save this KDA",
            "The enemy's net worth graph thanks them personally",
        ],
    ),
    (
        "award_ward_bot",
        &[
            "Vision wins games",
            "The real MVP wears a support badge",
            "If wards gave frequent flyer miles...",
            "Their minimap is brighter than their future",
            "Observer wards cost 0 gold and they STILL outspend everyone",
            "Dewarding is their love language",
            "They see everything — like Zeus ult but permanent",
            "Nightstalker hates this one player",
            "Even Clockwerk's Rocket Flare provides less vision",
            "The fog of war fears them",
        ],
    ),
    (
        "award_elo_inflation",
        &[
            "The grind paid off",
            "Rating go brrrr",
            "They can't keep getting away with this",
            "Climbing faster than a Broodmother up a cliff",
            "Their MMR trajectory is a Pudge hook — straight up",
            "Calibration was just the beginning",
            "From Herald to legend... literally",
            "The climb was steeper than high ground, but they took it",
            "Even Icefrog couldn't nerf this progression",
        ],
    ),
    (
        "award_the_cliff",
        &[
            "It's just a number, right?",
            "The descent was almost artistic",
            "Terminal velocity achieved",
            "Fell harder than a cliff-jungling Nature's Prophet",
            "Their rating graph is a Pudge hook — straight down",
            "Even Buyback couldn't save this trajectory",
            "Recalibration waiting room",
            "The matchmaker sent a sympathy card",
            "Dropped faster than a Divine Rapier on death",
        ],
    ),
    (
        "award_diamond_hands",
        &[
            "The house hates them",
            "Even the bookie tips their hat",
            "Professional gambler (don't tell HR)",
            "Printing JC like it's Alchemist's passive",
            "Better market reads than a Chen with Aghs",
            "Their portfolio is more stacked than a Medusa at 50 min",
            "The Oracle of Jopacoins",
            "Gambler's fallacy? Never heard of it. They just win.",
        ],
    ),
    (
        "award_house_favorite",
        &[
            "Thank you for your donation",
            "The bookie's best customer",
            "Subsidizing everyone else's winnings since day 1",
            "Their JC keeps the economy alive",
            "Donating to the house like a Bounty Hunter donating Track gold",
            "The economy's unsung hero",
            "Without them, the house would go bankrupt",
            "They bet like they play — with reckless abandon",
        ],
    ),
    (
        "award_degen_supreme",
        &[
            "All in, every time",
            "Gambling is a personality trait at this point",
            "The casino sends you Christmas cards",
            "Bets on everything including the coin flip",
            "Their gambling history is longer than a Techies game",
            "The Degen Score was invented because of them",
            "Divine Rapier of gambling — all or nothing",
            "Even Ogre Magi's Multicast RNG is more responsible",
        ],
    ),
    (
        "award_one_trick",
        &[
            "Comfort zone champion",
            "Ban this hero and watch them crumble",
            "One hero to rule them all",
            "Their hero pool is a hero puddle",
            "First pick, last pick, only pick",
            "Dotabuff thinks they only own one hero",
            "This hero is their entire personality",
            "They've memorized every voice line. All of them.",
        ],
    ),
    (
        "award_no_life",
        &[
            "Touch grass? What's that?",
            "The queue button has PTSD from you",
            "Do you have a job? Genuine question",
            "More games than TI has prize pool dollars",
            "They queue like Axe spins — constantly",
            "Their Steam hours would make a speedrunner blush",
            "Even the Ancients ask for a break",
            "Dota IS the social life",
        ],
    ),
    (
        "award_punching_bag",
        &[
            "The market has spoken",
            "Betting against them is basically free money",
            "Professional underdog",
            "The community's most trusted fade target",
            "Their name on the bet slip means 'easy money'",
            "Even Bounty Hunter tracks them for the payout",
            "The bookies' favorite content",
            "Losing is an art form and they're Picasso",
        ],
    ),
    (
        "award_steady_eddie",
        &[
            "Predictably average",
            "The metronome of matchmaking",
            "Consistency is its own reward",
            "Stable as a Tidehunter in Anchor Smash range",
            "Their performance graph is a flat line — in a good way?",
            "Neither feast nor famine — the anti-Alchemist",
            "Reliable like a Treant heal",
            "The BKB of players — solid, dependable, not flashy",
        ],
    ),
    (
        "award_coin_flip",
        &[
            "Every game is an adventure",
            "Schrödinger's teammate",
            "You never know which version shows up",
            "Volatile like a Chaos Knight with max phantasms",
            "Today: Immortal. Tomorrow: Herald. No in-between.",
            "Their form chart looks like a Puck's orb path",
            "Ogre Magi Multicast energy — sometimes 4x, sometimes 0x",
            "Even Faceless Void can't predict their next game",
        ],
    ),
    (
        "award_bankruptcy_speedrunner",
        &[
            "It's a lifestyle",
            "Financial ruin any% world record",
            "The bank has you on speed dial",
            "They speedrun bankruptcy like others speedrun Meepo combos",
            "Their JC balance respawns as fast as they lose it",
            "Even Wraith King's skeletons have more economic stability",
            "The ultimate Rapier buyer — all in, all lost",
            "Bankruptcy is just a number to them",
        ],
    ),
    (
        "award_jack_of_all_trades",
        &[
            "Master of... some?",
            "Their hero pool needs its own zip code",
            "Variety is the spice of feeding",
            "Draft phase? Just random and pray.",
            "More hero variety than a TI grand final",
            "They've played heroes most people forgot exist",
            "The ultimate flex pick — for better or worse",
            "Even Invoker doesn't have this many options",
        ],
    ),
    (
        "award_touched_grass",
        &[
            "Has a life outside Dota",
            "The rare casual sighting",
            "Quality over quantity, apparently",
            "They play Dota like it's a seasonal event",
            "Even couriers log more game time",
            "Their queue cooldown is measured in weeks",
            "Casually casual",
            "The lobby misses them. Kind of.",
        ],
    ),
    (
        "award_xp_vacuum",
        &[
            "Levels ahead, brain behind",
            "Outleveling everyone including their own team",
            "Tome of Knowledge in human form",
            "They absorb XP like a Black Hole",
            "Even Meepo is jealous of this XP gain",
            "Level 25 while everyone else is level 18",
            "Their Talent Tree is always fully unlocked first",
            "XPM so high it should be nerfed",
        ],
    ),
    (
        "award_serial_killer",
        &[
            "Violence IS the answer",
            "Their kill count has a kill count",
            "The Aegis of the Immortal fears them",
            "More kills than a Phantom Assassin with Daedalus",
            "The kill feed is their personal blog",
            "Even Bloodseeker can't keep up with this body count",
            "Godlike streak? More like a lifestyle.",
            "Their kill participation is their entire personality",
        ],
    ),
    (
        "award_assist_machine",
        &[
            "Always there for the cleanup crew",
            "The real carry was the assists we made along the way",
            "Force Staff into every fight",
            "They touch every kill like a Bounty Hunter Track",
            "Assists? They call it 'team participation'",
            "The ultimate setup player — like a Rubick with stolen spells",
            "Their KDA ratio is carried entirely by the A",
            "Glimmer Cape, Force Staff, save, repeat",
        ],
    ),
    (
        "award_win_merchant",
        &[
            "They just win. That's it. That's the tweet.",
            "The matchmaker's nightmare",
            "Team diff personified",
            "Winning is their default setting",
            "They queue and the lobby trembles",
            "Built like a last-pick Broodmother — unstoppable",
            "Their win rate defies mathematical logic",
            "The lobby's final boss",
        ],
    ),
    (
        "award_charity_case",
        &[
            "They play so others may win",
            "Free MMR dispenser",
            "Morale support for the enemy team",
            "Their losses fund the enemy's win streaks",
            "The ultimate space creator — for the wrong team",
            "Even neutral creeps have a better record",
            "They try. That's what matters. Apparently.",
            "Participation trophy energy",
        ],
    ),
    (
        "award_fantasy_king",
        &[
            "TI fantasy draft energy",
            "If only fantasy points were real money",
            "The stats don't lie",
            "Their stat line reads like a Dotabuff highlight reel",
            "Fantasy points stacked higher than a triple-stacked camp",
            "If Dota had an All-Star game, they'd be captain",
            "Numbers don't lie — this player is built different",
            "The spreadsheet hero",
        ],
    ),
];
